name: tox
on:
  push:
  pull_request:
  schedule:
    - cron: "0 8 * * *" # Every day at 8am UTC

concurrency:
  group: tox-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test with Python ${{ matrix.py }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        py:
          - "3.12"
          - "3.11"
          - "3.10"
        os:
          - ubuntu-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup python for test ${{ matrix.py }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.py }}
      - name: Install PDM
        run: python -m pip install pdm
      - name: Install dependencies
        run: pdm install --no-lock
      - name: Run tox
        run: pdm run tox
